DROP view app_search;
DROP TABLE test_entity ;
DROP TABLE App_Version ;
DROP TABLE localized ;
DROP TABLE locale ;
DROP TABLE app_category ;
DROP TABLE category ;
DROP TABLE app ;
DROP TABLE repo;
DROP TABLE "flyway_schema_history";
