drop view app_search;
drop table test_entity ;
drop table APP_HARDWARE;
drop table HARDWARE_PROFILE;
drop table App_Version ;
drop table localized ;
drop table locale ;
drop table app_category ;
drop table category ;
drop table app ;
drop table repo;
drop table "flyway_schema_history";
